export const LOAD_CHARACTERS = 'LOAD_CHARACTERS';
export const LOAD_CHARACTER = 'LOAD_CHARACTER';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const TOGGLE_FAVOURITE = 'TOGGLE_FAVOURITE';
export const LOAD_FAVOURITES = 'LOAD_FAVOURITES';
