// This file is auto-generated by wix-one-app-engine

export default {
  'wix-one-app-platform': () => require('wix-one-app-platform').default,
  'breakingbadapp': () => require('breakingbadapp').default,
  'template-demo-module': () => require('template-demo-module').default
}
;