export const testIDs = {
  CHARACTER_TITLE: 'CHARACTER_TITLE',
  CHARACTER_LIST: 'CHARACTER_LIST',
  CHARACTER_NAME: (characterID: string) => `CHARACTER_NAME${characterID}`,
  CHARACTER_IMAGE: 'CHARACTER_IMAGE',
};
