// This file is auto-generated by wix-one-app-engine

export default {
  'wix-one-app-platform': () => require('/Users/lukasa/coding/BreakingBadRNApp/BreakingBadApp/node_modules/wix-one-app-platform/module.admin.json'),
  'breakingbadapp': () => require('/Users/lukasa/coding/BreakingBadRNApp/BreakingBadApp/module.admin.json'),
  'template-demo-module': () => require('/Users/lukasa/coding/BreakingBadRNApp/BreakingBadApp/demo/module.admin.json'),
  '@wix/wix-one-app-member-view': () => require('/Users/lukasa/coding/BreakingBadRNApp/BreakingBadApp/node_modules/@wix/wix-one-app-member-view/module.admin.json')
};